return {
  normal = {
    {
      "<C-i><C-t>",
      "<cmd>GpChatNew tabnew<cr>",
      group = "AI",
      desc = "New Chat tabnew",
      nowait = true,
      remap = false,
    },
    { "<C-i><C-v>", "<cmd>GpChatNew vsplit<cr>",    desc = "New Chat vsplit",          nowait = true, remap = false },
    { "<C-i><C-x>", "<cmd>GpChatNew split<cr>",     desc = "New Chat split",           nowait = true, remap = false },
    { "<C-i>a",     "<cmd>GpAppend<cr>",            desc = "Append (after)",           nowait = true, remap = false },
    { "<C-i>b",     "<cmd>GpPrepend<cr>",           desc = "Prepend (before)",         nowait = true, remap = false },
    { "<C-i>c",     "<cmd>GpChatNew<cr>",           desc = "New Chat",                 nowait = true, remap = false },
    { "<C-i>f",     "<cmd>GpChatFinder<cr>",        desc = "Chat Finder",              nowait = true, remap = false },
    { "<C-i>g",     group = "generate into new ..", nowait = true,                     remap = false },
    { "<C-i>ge",    "<cmd>GpEnew<cr>",              desc = "GpEnew",                   nowait = true, remap = false },
    { "<C-i>gn",    "<cmd>GpNew<cr>",               desc = "GpNew",                    nowait = true, remap = false },
    { "<C-i>gp",    "<cmd>GpPopup<cr>",             desc = "Popup",                    nowait = true, remap = false },
    { "<C-i>gt",    "<cmd>GpTabnew<cr>",            desc = "GpTabnew",                 nowait = true, remap = false },
    { "<C-i>gv",    "<cmd>GpVnew<cr>",              desc = "GpVnew",                   nowait = true, remap = false },
    { "<C-i>n",     "<cmd>GpNextAgent<cr>",         desc = "Next Agent",               nowait = true, remap = false },
    { "<C-i>r",     "<cmd>GpRewrite<cr>",           desc = "Inline Rewrite",           nowait = true, remap = false },
    { "<C-i>s",     "<cmd>GpStop<cr>",              desc = "GpStop",                   nowait = true, remap = false },
    { "<C-i>t",     "<cmd>GpChatToggle<cr>",        desc = "Toggle Chat",              nowait = true, remap = false },
    { "<C-i>w",     group = "Whisper",              nowait = true,                     remap = false },
    { "<C-i>wa",    "<cmd>GpWhisperAppend<cr>",     desc = "Whisper Append (after)",   nowait = true, remap = false },
    { "<C-i>wb",    "<cmd>GpWhisperPrepend<cr>",    desc = "Whisper Prepend (before)", nowait = true, remap = false },
    { "<C-i>we",    "<cmd>GpWhisperEnew<cr>",       desc = "Whisper Enew",             nowait = true, remap = false },
    { "<C-i>wn",    "<cmd>GpWhisperNew<cr>",        desc = "Whisper New",              nowait = true, remap = false },
    { "<C-i>wp",    "<cmd>GpWhisperPopup<cr>",      desc = "Whisper Popup",            nowait = true, remap = false },
    { "<C-i>wr",    "<cmd>GpWhisperRewrite<cr>",    desc = "Whisper Inline Rewrite",   nowait = true, remap = false },
    { "<C-i>wt",    "<cmd>GpWhisperTabnew<cr>",     desc = "Whisper Tabnew",           nowait = true, remap = false },
    { "<C-i>wv",    "<cmd>GpWhisperVnew<cr>",       desc = "Whisper Vnew",             nowait = true, remap = false },
    { "<C-i>ww",    "<cmd>GpWhisper<cr>",           desc = "Whisper",                  nowait = true, remap = false },
    { "<C-i>x",     "<cmd>GpContext<cr>",           desc = "Toggle GpContext",         nowait = true, remap = false },
  },
  insert = {
    mode = { "i" },
    { "<C-i><C-t>", "<cmd>GpChatNew tabnew<cr>",    desc = "New Chat tabnew",          nowait = true, remap = false },
    { "<C-i><C-v>", "<cmd>GpChatNew vsplit<cr>",    desc = "New Chat vsplit",          nowait = true, remap = false },
    { "<C-i><C-x>", "<cmd>GpChatNew split<cr>",     desc = "New Chat split",           nowait = true, remap = false },
    { "<C-i>a",     "<cmd>GpAppend<cr>",            desc = "Append (after)",           nowait = true, remap = false },
    { "<C-i>b",     "<cmd>GpPrepend<cr>",           desc = "Prepend (before)",         nowait = true, remap = false },
    { "<C-i>c",     "<cmd>GpChatNew<cr>",           desc = "New Chat",                 nowait = true, remap = false },
    { "<C-i>f",     "<cmd>GpChatFinder<cr>",        desc = "Chat Finder",              nowait = true, remap = false },
    { "<C-i>g",     group = "generate into new ..", nowait = true,                     remap = false },
    { "<C-i>ge",    "<cmd>GpEnew<cr>",              desc = "GpEnew",                   nowait = true, remap = false },
    { "<C-i>gn",    "<cmd>GpNew<cr>",               desc = "GpNew",                    nowait = true, remap = false },
    { "<C-i>gp",    "<cmd>GpPopup<cr>",             desc = "Popup",                    nowait = true, remap = false },
    { "<C-i>gt",    "<cmd>GpTabnew<cr>",            desc = "GpTabnew",                 nowait = true, remap = false },
    { "<C-i>gv",    "<cmd>GpVnew<cr>",              desc = "GpVnew",                   nowait = true, remap = false },
    { "<C-i>n",     "<cmd>GpNextAgent<cr>",         desc = "Next Agent",               nowait = true, remap = false },
    { "<C-i>r",     "<cmd>GpRewrite<cr>",           desc = "Inline Rewrite",           nowait = true, remap = false },
    { "<C-i>s",     "<cmd>GpStop<cr>",              desc = "GpStop",                   nowait = true, remap = false },
    { "<C-i>t",     "<cmd>GpChatToggle<cr>",        desc = "Toggle Chat",              nowait = true, remap = false },
    { "<C-i>w",     group = "Whisper",              nowait = true,                     remap = false },
    { "<C-i>wa",    "<cmd>GpWhisperAppend<cr>",     desc = "Whisper Append (after)",   nowait = true, remap = false },
    { "<C-i>wb",    "<cmd>GpWhisperPrepend<cr>",    desc = "Whisper Prepend (before)", nowait = true, remap = false },
    { "<C-i>we",    "<cmd>GpWhisperEnew<cr>",       desc = "Whisper Enew",             nowait = true, remap = false },
    { "<C-i>wn",    "<cmd>GpWhisperNew<cr>",        desc = "Whisper New",              nowait = true, remap = false },
    { "<C-i>wp",    "<cmd>GpWhisperPopup<cr>",      desc = "Whisper Popup",            nowait = true, remap = false },
    { "<C-i>wr",    "<cmd>GpWhisperRewrite<cr>",    desc = "Whisper Inline Rewrite",   nowait = true, remap = false },
    { "<C-i>wt",    "<cmd>GpWhisperTabnew<cr>",     desc = "Whisper Tabnew",           nowait = true, remap = false },
    { "<C-i>wv",    "<cmd>GpWhisperVnew<cr>",       desc = "Whisper Vnew",             nowait = true, remap = false },
    { "<C-i>ww",    "<cmd>GpWhisper<cr>",           desc = "Whisper",                  nowait = true, remap = false },
    { "<C-i>x",     "<cmd>GpContext<cr>",           desc = "Toggle GpContext",         nowait = true, remap = false },
  },
  visual = {
    mode = { "v" },
    {
      "<C-i><C-t>",
      ":<C-u>'<,'>GpChatNew tabnew<cr>",
      desc = "Visual Chat New tabnew",
      nowait = true,
      remap = false,
    },
    {
      "<C-i><C-v>",
      ":<C-u>'<,'>GpChatNew vsplit<cr>",
      desc = "Visual Chat New vsplit",
      nowait = true,
      remap = false,
    },
    {
      "<C-i><C-x>",
      ":<C-u>'<,'>GpChatNew split<cr>",
      desc = "Visual Chat New split",
      nowait = true,
      remap = false,
    },
    {
      "<C-i>a",
      ":<C-u>'<,'>GpAppend<cr>",
      desc = "Visual Append (after)",
      nowait = true,
      remap = false,
    },
    {
      "<C-i>b",
      ":<C-u>'<,'>GpPrepend<cr>",
      desc = "Visual Prepend (before)",
      nowait = true,
      remap = false,
    },
    {
      "<C-i>c",
      ":<C-u>'<,'>GpChatNew<cr>",
      desc = "Visual Chat New",
      nowait = true,
      remap = false,
    },
    { "<C-i>g", group = "generate into new ..", nowait = true, remap = false },
    {
      "<C-i>ge",
      ":<C-u>'<,'>GpEnew<cr>",
      desc = "Visual GpEnew",
      nowait = true,
      remap = false,
    },
    {
      "<C-i>gn",
      ":<C-u>'<,'>GpNew<cr>",
      desc = "Visual GpNew",
      nowait = true,
      remap = false,
    },
    {
      "<C-i>gp",
      ":<C-u>'<,'>GpPopup<cr>",
      desc = "Visual Popup",
      nowait = true,
      remap = false,
    },
    {
      "<C-i>gt",
      ":<C-u>'<,'>GpTabnew<cr>",
      desc = "Visual GpTabnew",
      nowait = true,
      remap = false,
    },
    {
      "<C-i>gv",
      ":<C-u>'<,'>GpVnew<cr>",
      desc = "Visual GpVnew",
      nowait = true,
      remap = false,
    },
    {
      "<C-i>i",
      ":<C-u>'<,'>GpImplement<cr>",
      desc = "Implement selection",
      nowait = true,
      remap = false,
    },
    {
      "<C-i>n",
      "<cmd>GpNextAgent<cr>",
      desc = "Next Agent",
      nowait = true,
      remap = false,
    },
    {
      "<C-i>p",
      ":<C-u>'<,'>GpChatPaste<cr>",
      desc = "Visual Chat Paste",
      nowait = true,
      remap = false,
    },
    {
      "<C-i>r",
      ":<C-u>'<,'>GpRewrite<cr>",
      desc = "Visual Rewrite",
      nowait = true,
      remap = false,
    },
    {
      "<C-i>s",
      "<cmd>GpStop<cr>",
      desc = "GpStop",
      nowait = true,
      remap = false,
    },
    {
      "<C-i>t",
      ":<C-u>'<,'>GpChatToggle<cr>",
      desc = "Visual Toggle Chat",
      nowait = true,
      remap = false,
    },
    { "<C-i>w", group = "Whisper",              nowait = true, remap = false },
    {
      "<C-i>wa",
      ":<C-u>'<,'>GpWhisperAppend<cr>",
      desc = "Whisper Append (after)",
      nowait = true,
      remap = false,
    },
    {
      "<C-i>wb",
      ":<C-u>'<,'>GpWhisperPrepend<cr>",
      desc = "Whisper Prepend (before)",
      nowait = true,
      remap = false,
    },
    {
      "<C-i>we",
      ":<C-u>'<,'>GpWhisperEnew<cr>",
      desc = "Whisper Enew",
      nowait = true,
      remap = false,
    },
    {
      "<C-i>wn",
      ":<C-u>'<,'>GpWhisperNew<cr>",
      desc = "Whisper New",
      nowait = true,
      remap = false,
    },
    {
      "<C-i>wp",
      ":<C-u>'<,'>GpWhisperPopup<cr>",
      desc = "Whisper Popup",
      nowait = true,
      remap = false,
    },
    {
      "<C-i>wr",
      ":<C-u>'<,'>GpWhisperRewrite<cr>",
      desc = "Whisper Rewrite",
      nowait = true,
      remap = false,
    },
    {
      "<C-i>wt",
      ":<C-u>'<,'>GpWhisperTabnew<cr>",
      desc = "Whisper Tabnew",
      nowait = true,
      remap = false,
    },
    {
      "<C-i>wv",
      ":<C-u>'<,'>GpWhisperVnew<cr>",
      desc = "Whisper Vnew",
      nowait = true,
      remap = false,
    },
    {
      "<C-i>ww",
      ":<C-u>'<,'>GpWhisper<cr>",
      desc = "Whisper",
      nowait = true,
      remap = false,
    },
    {
      "<C-i>x",
      ":<C-u>'<,'>GpContext<cr>",
      desc = "Visual GpContext",
      nowait = true,
      remap = false,
    },
  },
}
