if [ "$(uname -s)" = "Darwin" ]; then
  OS="OSX"
  PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"
  MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
else
  OS=$(uname -s)
fi

## set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
  debian_chroot=$(cat /etc/debian_chroot)
fi

## enable color support of ls and also add handy aliases
# test -r ~/.dir_colors && eval "$(dircolors -b ~/.dir_colors)" || eval "$(dircolors -b)"

## Disable flow control. Ctrl-s + Ctrl-q
stty stop ''
stty start ''
stty -ixon
stty -ixoff

## Map capslock to ctrl
if which setxkbmap > /dev/null; then
  setxkbmap -layout us -option ctrl:nocaps
fi

## NodeJs bin
export PATH=./node_modules/.bin:$PATH

## Rust
. "$HOME/.cargo/env"

for DOTFILE in $HOME/dotfiles/system/.{function,env,alias,grep,prompt,nvm}; do
  [ -f "$DOTFILE" ] && . "$DOTFILE"
done

# Awesome command search
if [ -f ~/.fzf.bash ]; then
  source ~/.fzf.bash
fi

eval "$(/opt/homebrew/bin/brew shellenv)"

# Rbenv
export PATH="$HOME/.rbenv/bin:$PATH"

# pnpm autocompletion
# More info: https://pnpm.io/completio
# tabtab source for packages
# uninstall by removing these lines
[ -f ~/.config/tabtab/bash/__tabtab.bash ] && . ~/.config/tabtab/bash/__tabtab.bash || true

# pnpm
export PNPM_HOME="/Users/andres/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# PHP composer
export PATH=~/.composer/vendor/bin:$PATH

eval "$(rbenv init -)"
