# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Plugins
plugins=(
  macos
  ag
  git
  tmux
  bundler
  rbenv
  ruby
  virtualenv
  virtualenvwrapper
  zsh-syntax-highlighting
)

# Includes
source "$ZSH/custom/alias.zsh"
source "$ZSH/custom/fzf.zsh"
source "$ZSH/custom/virtualenvwrapper.zsh"

source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

source ~/.fzf.zsh
source ~/.nvm/nvm.sh
export PNPM_HOME="/Users/andres/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
export PATH="$PATH:/Users/andres/Library/pnpm/global/5/node_modules"
