# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Plugins
plugins=(
  macos
  # ag
  git
  tmux
  bundler
  rbenv
  ruby
  virtualenv
  virtualenvwrapper
  zsh-syntax-highlighting
  zsh-nvm
)

# Includes
source "$ZSH/custom/alias.zsh"
source "$ZSH/custom/fzf.zsh"
source "$ZSH/custom/virtualenvwrapper.zsh"

source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

source ~/.fzf.zsh

export PATH="$PATH:/Users/andres/Library/pnpm/global/5/node_modules"

# Put NVM path over pnpm path
NVM_VERSION=$(<"$NVM_DIR/alias/default")
export PATH="$NVM_DIR/versions/node/$NVM_VERSION/bin:$PATH"

# Use homebrew curl
export PATH="/opt/homebrew/opt/curl/bin:$PATH"


# bun completions
[ -s "/Users/andres/.bun/_bun" ] && source "/Users/andres/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# Fix git co [path with () or []]
unsetopt nomatch
